### PR TITLE
[AC-7355] Merge django-tablib changes from upstream repo

### PR DESCRIPTION
**Pull request by kaymation**
[JIRA](https://masschallenge.atlassian.net/browse/AC-7355)

we are having issues with django tablib. 
The original repository is [here](https://github.com/joshourisman/django-tablib)

Since we are dependent on a patch introduced by [this repo](https://github.com/mscam/django-tablib)

i propose we update with the latter repo instead

### CODE REVIEW

**Comment by pbx** [comment]
@kaymation - Since GitHub's metadata records our fork as coming from the `joshourisman` repo, but we're now switching to regarding the `mscam` fork as our origin, how about we  use `git remote add upstream` to set our upstream repo accordingly? ([GitHub docs on this](https://help.github.com/en/github/getting-started-with-github/fork-a-repo#keep-your-fork-synced))

**Comment by kaymation** [comment]
@pbx upstream repo set to 
https://github.com/mscam/django-tablib.git

**Comment by pbx** [comment]
Thanks @kaymation. Unfortunately it looks like there is no way to get this change reflected in our origin repo. I.e. the `git remote add upstream` invocation does change the local clone (so when you do `git remote -v` the output includes the `upstream` repo you added), but there's no commit to `git push`; that change is only in effect in the clone where it was made.

Looks like the only way to update the origin (Github) repo is to delete and recreate it. We should have @shanbady weigh in on whether he thinks that's worthwhile. https://stackoverflow.com/a/17366793/86233

The reason I'm pushing to get this correct is, we've lost track of what we're doing with this repo a couple times. We had a fork but weren't using it, then switched to using our fork, then accidentally switched back to the upstream. Pointing our fork to the correct upstream (rather than just trying to remember, or adding a note to its README or something) seems like reasonable insurance against messing it up again.

**Comment by shanbady** [comment]
@kaymation @pbx  it seems like we had already merged the upstream changes at some point. If we look at our master and compare it to the upstream master it shows the changes from AC-7355: https://github.com/joshourisman/django-tablib/compare/master...masschallenge:master

**Comment by pbx** [comment]
@shanbady - right, the point here is that the `joshourisman` repo is missing the bugfix but the `mscam` fork has it, and hence makes a better upstream for us. https://github.com/joshourisman/django-tablib/compare/master...mscam:master

**Comment by shanbady** [comment]
@pbx ah i see. In that case I think I'd go with the delete and re-fork route unless we've customized this repo somehow.

**Comment by pbx** [comment]
@kaymation what's the state of this work?

**Pull request closed without merging**
